# Numpy and its Functions

In [1]:
import numpy as np

In [2]:
emp_salary=np.random.randint(8,70,10)

In [3]:
emp_salary

array([17, 58, 40, 69, 55, 21, 23, 62, 66, 18])

In [4]:
#set minimum and maximum salary using a_min and a_max 

In [5]:
np.clip(emp_salary,a_min=20,a_max=50)# if we use clip method then all maximum and minimum value we can set as per our use

array([20, 50, 40, 50, 50, 21, 23, 50, 50, 20])

In [6]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [7]:
print(np.where(emp_salary <25))

(array([0, 5, 6, 9]),)


In [8]:
#If you want to see actual data, use index 

In [9]:
emp_salary[[1,4]]

array([58, 55])

In [10]:
#similarly you can  check for any condition (<,>,=,==,<=,>=)

In [11]:
#Reshaping Otherways

In [12]:
import numpy as np
from numpy.random import randint as ri

In [13]:
a=ri(1,99,30)
print(a)

[82 89 22 69  1 10 12 60 67 74 31 40 66  5 87 97 43  9 53  8 85 96 94 98
 20 33 66 25 75 67]


In [14]:
b=a.reshape(2,3,5)
print(b)

[[[82 89 22 69  1]
  [10 12 60 67 74]
  [31 40 66  5 87]]

 [[97 43  9 53  8]
  [85 96 94 98 20]
  [33 66 25 75 67]]]


In [15]:
c=a.reshape(6,5)
print(c)

[[82 89 22 69  1]
 [10 12 60 67 74]
 [31 40 66  5 87]
 [97 43  9 53  8]
 [85 96 94 98 20]
 [33 66 25 75 67]]


In [16]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  1
Maximum of a is  98


## Sorting 

In [17]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[73 94 36 64 42]
 [24 14 11 91 88]
 [53 66 29 73 52]
 [20 59 90 83 60]
 [55 73 15 59  1]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[36 42 64 73 94]
 [11 14 24 88 91]
 [29 52 53 66 73]
 [20 59 60 83 90]
 [ 1 15 55 59 73]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[20 14 11 59  1]
 [24 59 15 64 42]
 [53 66 29 73 52]
 [55 73 36 83 60]
 [73 94 90 91 88]]


In [18]:
# Index and slicing

In [19]:
arr=np.arange(13,30)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [20]:
print("Element of 7th index is =",arr[7])

Element of 7th index is = 20


In [21]:
print("Element of 3rd and 5th index is = ",arr[3:5])

Element of 3rd and 5th index is =  [16 17]


In [22]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [23]:
#Store arr in abc and check upto 4th index of abc

In [24]:
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [25]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [26]:
print("7th elemets from last backword are : ",arr[-1:-8:-1])

7th elemets from last backword are :  [29 28 27 26 25 24 23]


In [27]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])#Pass a list as a index to subset

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [28]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print("Entire row at index 2: ",mat[2])

Entire row at index 2:  [7 8 9]


In [30]:
print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [31]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [32]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]


In [34]:
#Update Matrix

In [35]:
print("Original Matrix \n\n",mat)

Original Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
mat[0,2]=200

In [37]:
mat

array([[  1,   2, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [38]:
mat[1,0]=100

In [39]:
mat

array([[  1,   2, 200],
       [100,   5,   6],
       [  7,   8,   9]])

## Subsetting
Subsetting means when we want to fetch only few data from matrix.

In [40]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[46 28 56 49 47]
 [28 51 64 84 47]
 [33 73 48 73 36]]


In [41]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [56 51 64 84 73 73]


In [42]:
print(np.where(mat==98))

(array([], dtype=int64), array([], dtype=int64))


In [43]:
#You can also use np.where to return some data based on condtion

In [44]:
age=50
np.where(age>68,'Retired','Still Working')

array('Still Working', dtype='<U13')

## Universal Functions

In [45]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrics of Single digit number \n---------------\n",mat1)
print("\n 2st Matrics of Single digit number \n---------------\n",mat2)


 1st Matrics of Single digit number 
---------------
 [[1 3 9]
 [2 5 3]
 [3 7 6]]

 2st Matrics of Single digit number 
---------------
 [[2 7 4]
 [6 9 7]
 [5 5 8]]


In [46]:
print('mat1=\n',mat1)
print('mat2=\n',mat2)

mat1=
 [[1 3 9]
 [2 5 3]
 [3 7 6]]
mat2=
 [[2 7 4]
 [6 9 7]
 [5 5 8]]


In [47]:
print("\n Division \n---------------------\n",mat1/mat2)


 Division 
---------------------
 [[0.5        0.42857143 2.25      ]
 [0.33333333 0.55555556 0.42857143]
 [0.6        1.4        0.75      ]]


In [48]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[-1 -5 19]
 [-6 -3 -5]
 [-1 11  2]]


## Broadcasting-
* NumPy operations are usually performed on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape. 
* However, NumPy broadcasting rules relax this constraint when the array shapes meet certain conditions. When operating on two arrays, NumPy compares their shapes element-wise, starting with the trailing dimensions and working its way forward. 
* Two dimensions are compatible when they are equal, or when one of them is 1.

In [50]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
#create a rank1 ndarray with 3 values

In [52]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [53]:
y=start+add_rows # add to each row of 'start' using broadcasting

In [54]:
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [55]:
new_row=add_rows.T # T is use for transpose it convert column into row #vice versa

In [56]:
new_row

array([[1],
       [0],
       [2]])

In [57]:
test=new_row+start
print(test)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [58]:
#craete table ndarray which is 4 X 1 to broadcast across coloumn

In [59]:
ad_cols=np.array([[0,2,2,3]])

In [60]:
ad_cols=ad_cols.T

In [61]:
ad_cols

array([[0],
       [2],
       [2],
       [3]])

In [62]:
#Array Math

In [63]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrix of random single digit number\n---------------------------\n",mat1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",mat2)

print("\n sq-root of 1st Matrix using np\n",'-'*50,"\n",np.sqrt(mat1))
print("\n square of 2nd Matrix using np\n",'-'*50,"\n",np.square(mat2))


 1st Matrix of random single digit number
---------------------------
 [[5 6 4]
 [2 3 9]
 [2 2 2]]

 2nd Matrix of random single digit number
---------------------------
 [[9 7 7]
 [2 5 3]
 [5 4 9]]

 sq-root of 1st Matrix using np
 -------------------------------------------------- 
 [[2.23606798 2.44948974 2.        ]
 [1.41421356 1.73205081 3.        ]
 [1.41421356 1.41421356 1.41421356]]

 square of 2nd Matrix using np
 -------------------------------------------------- 
 [[81 49 49]
 [ 4 25  9]
 [25 16 81]]
